name:        pantry
version:     0.8.2.2
synopsis:    Content addressable Haskell package management
description: Please see the README on GitHub at <https://github.com/commercialhaskell/pantry#readme>
category:    Development
author:      Michael Snoyman
maintainer:  michael@snoyman.com
copyright:   2018-2022 FP Complete
license:     BSD3
github:      commercialhaskell/pantry

extra-source-files:
- README.md
- ChangeLog.md
- attic/hpack-0.1.2.3.tar.gz
- attic/package-0.1.2.3.tar.gz
- attic/symlink-to-dir.tar.gz

flags:
  test-pretty-exceptions:
    description: Build an executable to test pretty exceptions
    default: false
    manual: false

dependencies:
- base >=4.10 && < 5
- aeson
- ansi-terminal
- bytestring
- Cabal >= 3 && < 3.11
- casa-client
- casa-types
- conduit
- conduit-extra
- containers
- cryptonite
- cryptonite-conduit
- digest
- filelock
- generic-deriving
- hackage-security
- hpack >= 0.35.1
- http-client
- http-client-tls
- http-conduit
- http-download
- http-types
- memory
- mtl
- network-uri
- path
- path-io
- persistent
- persistent-sqlite >= 2.9.3
- persistent-template
- primitive
- resourcet
- rio
- rio-orphans
- rio-prettyprint
- tar-conduit
- text
- text-metrics
- time
- transformers
- unix-compat
- unliftio
- unordered-containers
- vector
- yaml
- zip-archive

# See https://github.com/haskell/network/pull/552.
when:
  condition: impl(ghc >= 9.4.5) && os(windows)
  dependencies: network >= 3.1.2.9

ghc-options:
  - -Wall

library:
  source-dirs: src/
  when:
  - condition: 'os(windows)'
    then:
      source-dirs: src/windows/
    else:
      source-dirs: src/unix/

  exposed-modules:
  - Pantry
  - Pantry.SHA256

  # For testing
  - Pantry.Internal
  - Pantry.Internal.StaticBytes

  # For stackage-server
  - Pantry.Internal.Stackage

  # For stack
  - Pantry.Internal.Companion
  - Pantry.Internal.AesonExtended

  other-modules:
  - Hackage.Security.Client.Repository.HttpLib.HttpClient
  - Pantry.Archive
  - Pantry.HTTP
  - Pantry.HPack
  - Pantry.Hackage
  - Pantry.Repo
  - Pantry.SQLite
  - Pantry.Storage
  - Pantry.Casa
  - Pantry.Tree
  - Pantry.Types

executables:
  test-pretty-exceptions:
    when:
    - condition: "!flag(test-pretty-exceptions)"
      buildable: false
    - condition: 'os(windows)'
      then:
        source-dirs: app/test-pretty-exceptions/windows/
        dependencies:
        - process
        - Win32
      else:
        source-dirs: app/test-pretty-exceptions/unix/
    main: Main.hs
    source-dirs: app/test-pretty-exceptions
    dependencies:
    - pantry
    - optparse-applicative

tests:
  spec:
    source-dirs: test
    main: Spec.hs
    dependencies:
    - pantry
    - exceptions
    - hedgehog
    - hspec
    - QuickCheck
    - raw-strings-qq
