name: pantry
version: 0.9.3.3
synopsis: Content addressable Haskell package management
description: Please see the README on GitHub at <https://github.com/commercialhaskell/pantry#readme>
category: Development
author: Michael Snoyman
maintainer: michael@snoyman.com
copyright: 2018-2022 FP Complete
license: BSD3
github: commercialhaskell/pantry

extra-source-files:
- CONTRIBUTING.md
- README.md
- ChangeLog.md
- attic/hpack-0.1.2.3.tar.gz
- attic/package-0.1.2.3.tar.gz
- attic/symlink-to-dir.tar.gz

flags:
  test-pretty-exceptions:
    description: Build an executable to test pretty exceptions
    default: false
    manual: false

dependencies:
- base >= 4.13 && < 5
- aeson
- aeson-warning-parser >= 0.1.1
- ansi-terminal
- bytestring
- Cabal >= 3 && < 3.11
- casa-client >= 0.0.2
- casa-types
- companion
- conduit
- conduit-extra
- containers
- crypton
- crypton-conduit
- digest
- filelock
- generic-deriving
- hackage-security
- hpack >= 0.35.3
- http-client
- http-client-tls >= 0.3.6.2
- http-conduit
- http-download >= 0.2.1.0
- http-types
- memory
- mtl
- network-uri
- path
- path-io
- persistent
- persistent-sqlite >= 2.9.3
- persistent-template
- primitive
- resourcet
- rio
- rio-orphans
- rio-prettyprint >= 0.1.7.0
- static-bytes
- tar-conduit >= 0.4.1
- text
- text-metrics
- time
- transformers
- unix-compat
- unliftio
- unordered-containers
- vector
- yaml
- zip-archive

# See https://github.com/haskell/network/pull/552.
when:
  condition: impl(ghc >= 9.4.5) && os(windows)
  dependencies: network >= 3.1.2.9

ghc-options:
- -fwrite-ide-info
- -hiedir=.hie
- -Wall

# For testing
internal-libraries:
  internal:
    source-dirs: int/

library:
  source-dirs: src/
  when:
  - condition: 'os(windows)'
    then:
      source-dirs: src/windows/
    else:
      source-dirs: src/unix/
  dependencies:
  - internal

  exposed-modules:
  - Pantry
  - Pantry.SQLite

  # For stackage-server, and stack testing
  - Pantry.Internal.Stackage

  reexported-modules:
  - Pantry.SHA256

  other-modules:
  - Hackage.Security.Client.Repository.HttpLib.HttpClient
  - Pantry.Archive
  - Pantry.HTTP
  - Pantry.Hackage
  - Pantry.Repo
  - Pantry.Storage
  - Pantry.Casa
  - Pantry.Tree

executables:
  test-pretty-exceptions:
    when:
    - condition: "!flag(test-pretty-exceptions)"
      buildable: false
    - condition: 'os(windows)'
      then:
        source-dirs: app/test-pretty-exceptions/windows/
        dependencies:
        - process
        - Win32
      else:
        source-dirs: app/test-pretty-exceptions/unix/
    main: Main.hs
    source-dirs: app/test-pretty-exceptions
    dependencies:
    - pantry
    - optparse-applicative

tests:
  spec:
    build-tools: hspec-discover
    source-dirs: test
    main: Spec.hs
    dependencies:
    - pantry
    - exceptions
    - hedgehog
    - hspec
    - QuickCheck
    - raw-strings-qq
    - internal
