name:        pantry
version:     0.5.1.4
synopsis:    Content addressable Haskell package management
description: Please see the README on Github at <https://github.com/commercialhaskell/pantry#readme>
category:    Development
author:      Michael Snoyman
maintainer:  michael@snoyman.com
copyright:   2018-2019 FP Complete
license:     BSD3
github:      commercialhaskell/pantry

extra-source-files:
- README.md
- ChangeLog.md
- attic/hpack-0.1.2.3.tar.gz
- attic/package-0.1.2.3.tar.gz
- attic/symlink-to-dir.tar.gz

dependencies:
- base >=4.10 && < 5
- ansi-terminal
- digest
- rio
- aeson
- text
- unordered-containers
- containers
- path
- transformers
- generic-deriving
- unliftio
- http-conduit
- http-client-tls
- http-download
- http-types
- http-client
- conduit
- bytestring
- network-uri
- hackage-security
- primitive
- vector
- memory
- cryptonite
- cryptonite-conduit
- persistent
- persistent-sqlite >= 2.9.3
- persistent-template
- Cabal >= 3 && < 3.3
- path-io
- rio-orphans
- conduit-extra
- tar-conduit
- time
- unix-compat
- hpack >= 0.31.2
- yaml
- zip-archive
- text-metrics
- resourcet
- rio-prettyprint
- mtl
- filelock
- casa-client
- casa-types

ghc-options:
  - -Wall

library:
  source-dirs: src/
  when:
  - condition: 'os(windows)'
    then:
      source-dirs: src/windows/
    else:
      source-dirs: src/unix/

  exposed-modules:
  - Pantry
  - Pantry.SHA256

  # For testing
  - Pantry.Internal
  - Pantry.Internal.StaticBytes

  # For stackage-server
  - Pantry.Internal.Stackage

  # For stack
  - Pantry.Internal.Companion
  - Pantry.Internal.AesonExtended

  other-modules:
  - Hackage.Security.Client.Repository.HttpLib.HttpClient
  - Pantry.Archive
  - Pantry.HTTP
  - Pantry.HPack
  - Pantry.Hackage
  - Pantry.Repo
  - Pantry.SQLite
  - Pantry.Storage
  - Pantry.Casa
  - Pantry.Tree
  - Pantry.Types

tests:
  spec:
    source-dirs: test
    main: Spec.hs
    dependencies:
    - pantry
    - hspec
    - exceptions
    - hedgehog
    - QuickCheck
    - raw-strings-qq
