# GHC 9.2.8
resolver: lts-20.26

extra-deps:
- rio-prettyprint-0.1.4.0@sha256:1f8eb3ead0ef33d3736d53e1de5e9b2c91a0c207cdca23321bd74c401e85f23a,1301

flags:
  ansi-terminal:
    win32-2-13-1: false
  mintty:
    win32-2-13-1: false

ghc-options:
  "$locals": -fhide-source-paths
