resolver: lts-14.20

extra-deps:
- Cabal-3.0.0.0
- hpack-0.33.0

- github: fpco/casa
  commit: fc0ed26858bfc4f2966ed2dfb2871bae9266dda6
  subdirs:
     - casa-client
     - casa-types

ghc-options:
   "$locals": -fhide-source-paths
