jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      stack-lts-14:
        BUILD: stack
        STACK_YAML: stack.yaml
        ARGS: --resolver lts-14
      stack-nightly:
        BUILD: stack
        STACK_YAML: stack-nightly.yaml
        ARGS: --resolver nightly
      #style:
      #  BUILD: style
    maxParallel: 6
  steps:
  - script: |
      export STACK_ROOT="$(Build.SourcesDirectory)"/.stack-root;
      mkdir -p ~/.local/bin
      curl -L https://github.com/commercialhaskell/stack/releases/download/v2.1.3/stack-2.1.3-linux-x86_64-static.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
      case "$BUILD" in
        style)
          PACKAGE=hlint
          echo "Downloading $PACKAGE now ..."

          RELEASES=$(curl --silent https://github.com/ndmitchell/$PACKAGE/releases)
          URL=https://github.com/$(echo "$RELEASES" | grep -o '\"[^\"]*-x86_64-linux\.tar\.gz\"' | sed s/\"//g | head -n1)
          VERSION=$(echo "$URL" | sed -e 's/.*-\([\.0-9]\+\)-x86_64-linux\.tar\.gz/\1/')

          curl --progress-bar --location -o"$PACKAGE.tar.gz" "$URL"
          tar -xzf "$PACKAGE.tar.gz" -C .
          mv "$PACKAGE-$VERSION" "$PACKAGE"
          export PATH="$(pwd)"/hlint:$PATH
          ;;
        *)
          export PATH=$HOME/.local/bin:$PATH
          stack --install-ghc $ARGS test --bench --only-dependencies
          ;;
      esac
      set -ex
      case "$BUILD" in
        style)
          hlint src/
          ;;
        *)
          stack $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
          ;;
      esac
      set +ex
    env:
      OS_NAME: ${{ parameters.os }}
    displayName: 'Installation ${{parameters.os}} & Test'
